version: '3'

services:
  web:
    build: /web
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html                                                         

  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d 
    environment:
      MYSQL_ROOT_PASSWORD: root
      allowPublicKeyRetrieval: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql